apiVersion: v1
kind: Pod
metadata:
  name: mysitepod
  labels:
        app: mysitepod
spec:
  containers:
  - name: tomcat
    image: "httpd"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysitesvc
  namespace: suv
spec:
  selector:
    app: mysitepod
  ports:
  - name: http
    port: 80
    protocol: TCP

---
# In  my Minikube, v1 version was not supporting hence used v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysiteingress
spec:
  rules:
  - host: myingress.192.168.59.100.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysitesvc
            port:
              number: 80
  ingressClassName: nginx
